on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2  # Updated to v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync files to S3
      run: aws s3 sync . s3://awsdemoo --delete  # Separate step for the S3 sync command
